/**
 * Generated by "@vuepress/internal-routes"
 */

import { injectComponentOption, ensureAsyncComponentsLoaded } from '@app/util'
import rootMixins from '@internal/root-mixins'
import GlobalLayout from "D:\\file\\githubWorkSpace\\技术文档\\dylin_techdocument\\node_modules\\@vuepress\\core\\lib\\client\\components\\GlobalLayout.vue"

injectComponentOption(GlobalLayout, 'mixins', rootMixins)
export const routes = [
  {
    name: "v-8b8f87b0",
    path: "/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-8b8f87b0").then(next)
    },
  },
  {
    path: "/index.html",
    redirect: "/"
  },
  {
    name: "v-7b5cc043",
    path: "/serverDocument/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-7b5cc043").then(next)
    },
  },
  {
    path: "/serverDocument/index.html",
    redirect: "/serverDocument/"
  },
  {
    name: "v-15555078",
    path: "/undivided/CompositionAPI.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-15555078").then(next)
    },
  },
  {
    name: "v-6e561bb8",
    path: "/undivided/commitLint.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-6e561bb8").then(next)
    },
  },
  {
    name: "v-11e48133",
    path: "/clientDocument/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-11e48133").then(next)
    },
  },
  {
    path: "/clientDocument/index.html",
    redirect: "/clientDocument/"
  },
  {
    name: "v-96596df4",
    path: "/undivided/ES6.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-96596df4").then(next)
    },
  },
  {
    name: "v-27d278a6",
    path: "/undivided/updateDoc.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-27d278a6").then(next)
    },
  },
  {
    name: "v-7a74c16e",
    path: "/undivided/lodash.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-7a74c16e").then(next)
    },
  },
  {
    name: "v-39dd134e",
    path: "/undivided/typeScript.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-39dd134e").then(next)
    },
  },
  {
    name: "v-4a168ef6",
    path: "/undivided/%E5%BE%AE%E5%89%8D%E7%AB%AF.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-4a168ef6").then(next)
    },
  },
  {
    path: "/undivided/微前端.html",
    redirect: "/undivided/%E5%BE%AE%E5%89%8D%E7%AB%AF.html"
  },
  {
    path: "/undivided/微前端.html",
    redirect: "/undivided/%E5%BE%AE%E5%89%8D%E7%AB%AF.html"
  },
  {
    name: "v-1c45c512",
    path: "/undivided/%E6%89%A9%E5%B1%95.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-1c45c512").then(next)
    },
  },
  {
    path: "/undivided/扩展.html",
    redirect: "/undivided/%E6%89%A9%E5%B1%95.html"
  },
  {
    path: "/undivided/扩展.html",
    redirect: "/undivided/%E6%89%A9%E5%B1%95.html"
  },
  {
    name: "v-f9c46a9a",
    path: "/undivided/%E7%86%9F%E6%82%89Webpack.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-f9c46a9a").then(next)
    },
  },
  {
    path: "/undivided/熟悉Webpack.html",
    redirect: "/undivided/%E7%86%9F%E6%82%89Webpack.html"
  },
  {
    path: "/undivided/熟悉Webpack.html",
    redirect: "/undivided/%E7%86%9F%E6%82%89Webpack.html"
  },
  {
    path: '*',
    component: GlobalLayout
  }
]