/**
 * Generated by "@vuepress/internal-site-data"
 */
export const siteData = {
  "title": "dylin_blog",
  "description": "个人技术文档，基于VuePress",
  "base": "/",
  "headTags": [
    [
      "link",
      {
        "rel": "icon",
        "href": "./img/logo.png"
      }
    ]
  ],
  "pages": [
    {
      "title": "Home",
      "frontmatter": {
        "home": true,
        "heroImage": "/img/logo.png",
        "heroText": "技术文档",
        "tagline": "dylin 欢迎您",
        "actionText": "前往 →",
        "actionLink": "/zh/guide/",
        "features": [
          {
            "title": null,
            "details": "个人开发学习的整理归纳，收入技术文档；基于vuePress，以 Markdown 为中心的项目结构。"
          },
          {
            "title": "Vue驱动",
            "details": "享受 Vue + webpack 的开发体验，在 Markdown 中使用 Vue 组件，同时可以使用 Vue 来开发自定义主题。"
          },
          {
            "title": "高性能",
            "details": "VuePress 为每个页面预渲染生成静态的 HTML，同时在页面被加载的时候，将作为 SPA 运行。"
          }
        ],
        "footer": "dylin | Copyright @2021"
      },
      "regularPath": "/",
      "relativePath": "README.md",
      "key": "v-8b8f87b0",
      "path": "/"
    },
    {
      "title": "服务端技术",
      "frontmatter": {},
      "regularPath": "/serverDocument/",
      "relativePath": "serverDocument/index.md",
      "key": "v-7b5cc043",
      "path": "/serverDocument/",
      "headers": [
        {
          "level": 2,
          "title": "什么都没写！",
          "slug": "什么都没写"
        }
      ]
    },
    {
      "title": "CompositionAPI",
      "frontmatter": {},
      "regularPath": "/undivided/CompositionAPI.html",
      "relativePath": "undivided/CompositionAPI.md",
      "key": "v-15555078",
      "path": "/undivided/CompositionAPI.html",
      "headers": [
        {
          "level": 3,
          "title": "CompositionAPI",
          "slug": "compositionapi"
        }
      ]
    },
    {
      "title": "commintList",
      "frontmatter": {},
      "regularPath": "/undivided/commitLint.html",
      "relativePath": "undivided/commitLint.md",
      "key": "v-6e561bb8",
      "path": "/undivided/commitLint.html",
      "headers": [
        {
          "level": 3,
          "title": "commintList",
          "slug": "commintlist"
        },
        {
          "level": 3,
          "title": "官方文档",
          "slug": "官方文档"
        },
        {
          "level": 3,
          "title": "安装",
          "slug": "安装"
        },
        {
          "level": 3,
          "title": "说明",
          "slug": "说明"
        },
        {
          "level": 3,
          "title": "配置",
          "slug": "配置"
        },
        {
          "level": 3,
          "title": "参考文档",
          "slug": "参考文档"
        }
      ]
    },
    {
      "title": "什么都没写！",
      "frontmatter": {},
      "regularPath": "/clientDocument/",
      "relativePath": "clientDocument/index.md",
      "key": "v-11e48133",
      "path": "/clientDocument/",
      "headers": [
        {
          "level": 2,
          "title": "什么都没写！",
          "slug": "什么都没写"
        }
      ]
    },
    {
      "title": "ES6(ES 2015)",
      "frontmatter": {},
      "regularPath": "/undivided/ES6.html",
      "relativePath": "undivided/ES6.md",
      "key": "v-96596df4",
      "path": "/undivided/ES6.html",
      "headers": [
        {
          "level": 3,
          "title": "ES6(ES 2015)",
          "slug": "es6-es-2015"
        },
        {
          "level": 2,
          "title": "一、let 和const",
          "slug": "一、let-和const"
        },
        {
          "level": 2,
          "title": "二、解构赋值",
          "slug": "二、解构赋值"
        },
        {
          "level": 2,
          "title": "三、模版字符串",
          "slug": "三、模版字符串"
        },
        {
          "level": 2,
          "title": "四、箭头函数",
          "slug": "四、箭头函数"
        },
        {
          "level": 2,
          "title": "五、参数默认值问题",
          "slug": "五、参数默认值问题"
        },
        {
          "level": 2,
          "title": "六、引入 rest参数，用于获取函数的实参",
          "slug": "六、引入-rest参数-用于获取函数的实参"
        },
        {
          "level": 2,
          "title": "七、扩展运算符",
          "slug": "七、扩展运算符"
        },
        {
          "level": 2,
          "title": "八、symbol",
          "slug": "八、symbol"
        },
        {
          "level": 2,
          "title": "九、迭代器(iterator)",
          "slug": "九、迭代器-iterator"
        },
        {
          "level": 2,
          "title": "十、生成器(generator)",
          "slug": "十、生成器-generator"
        }
      ]
    },
    {
      "title": "前端文档更新教程",
      "frontmatter": {},
      "regularPath": "/undivided/updateDoc.html",
      "relativePath": "undivided/updateDoc.md",
      "key": "v-27d278a6",
      "path": "/undivided/updateDoc.html",
      "headers": [
        {
          "level": 3,
          "title": "前端文档更新教程",
          "slug": "前端文档更新教程"
        }
      ]
    },
    {
      "title": "一、lodash  安装教程",
      "frontmatter": {},
      "regularPath": "/undivided/lodash.html",
      "relativePath": "undivided/lodash.md",
      "key": "v-7a74c16e",
      "path": "/undivided/lodash.html",
      "headers": [
        {
          "level": 2,
          "title": "一、lodash  安装教程",
          "slug": "一、lodash-安装教程"
        },
        {
          "level": 2,
          "title": "二、loadsh 的方法使用",
          "slug": "二、loadsh-的方法使用"
        },
        {
          "level": 3,
          "title": "1.数组方法",
          "slug": "_1-数组方法"
        },
        {
          "level": 3,
          "title": "2. 集合",
          "slug": "_2-集合"
        },
        {
          "level": 2,
          "title": "三、回顾数组的方法",
          "slug": "三、回顾数组的方法"
        },
        {
          "level": 3,
          "title": "1. 改变原数组",
          "slug": "_1-改变原数组"
        },
        {
          "level": 3,
          "title": "2. 不改变原数组",
          "slug": "_2-不改变原数组"
        }
      ]
    },
    {
      "title": "TypeScript基础",
      "frontmatter": {},
      "regularPath": "/undivided/typeScript.html",
      "relativePath": "undivided/typeScript.md",
      "key": "v-39dd134e",
      "path": "/undivided/typeScript.html",
      "headers": [
        {
          "level": 3,
          "title": "TypeScript基础",
          "slug": "typescript基础"
        },
        {
          "level": 3,
          "title": "1.安装",
          "slug": "_1-安装"
        },
        {
          "level": 3,
          "title": "2.将 TypeScript 转换为 JavaScript 代码",
          "slug": "_2-将-typescript-转换为-javascript-代码"
        },
        {
          "level": 3,
          "title": "3.使用 node 命令来执行 test.js 文件",
          "slug": "_3-使用-node-命令来执行-test-js-文件"
        },
        {
          "level": 3,
          "title": "4.基础类型以及声明",
          "slug": "_4-基础类型以及声明"
        },
        {
          "level": 3,
          "title": "5.TypeScript 联合类型",
          "slug": "_5-typescript-联合类型"
        },
        {
          "level": 3,
          "title": "6.TypeScript 接口",
          "slug": "_6-typescript-接口"
        }
      ]
    },
    {
      "title": "微前端",
      "frontmatter": {},
      "regularPath": "/undivided/%E5%BE%AE%E5%89%8D%E7%AB%AF.html",
      "relativePath": "undivided/微前端.md",
      "key": "v-4a168ef6",
      "path": "/undivided/%E5%BE%AE%E5%89%8D%E7%AB%AF.html",
      "headers": [
        {
          "level": 3,
          "title": "微前端",
          "slug": "微前端"
        }
      ]
    },
    {
      "title": "扩展",
      "frontmatter": {},
      "regularPath": "/undivided/%E6%89%A9%E5%B1%95.html",
      "relativePath": "undivided/扩展.md",
      "key": "v-1c45c512",
      "path": "/undivided/%E6%89%A9%E5%B1%95.html",
      "headers": [
        {
          "level": 3,
          "title": "扩展",
          "slug": "扩展"
        }
      ]
    },
    {
      "title": "熟悉Webpack",
      "frontmatter": {},
      "regularPath": "/undivided/%E7%86%9F%E6%82%89Webpack.html",
      "relativePath": "undivided/熟悉Webpack.md",
      "key": "v-f9c46a9a",
      "path": "/undivided/%E7%86%9F%E6%82%89Webpack.html",
      "headers": [
        {
          "level": 2,
          "title": "熟悉Webpack",
          "slug": "熟悉webpack"
        },
        {
          "level": 2,
          "title": "目的",
          "slug": "目的"
        },
        {
          "level": 2,
          "title": "传统的H5项目",
          "slug": "传统的h5项目"
        },
        {
          "level": 2,
          "title": "Webpack是什么？",
          "slug": "webpack是什么"
        },
        {
          "level": 3,
          "title": "WebPack和Grunt以及Gulp相比有什么特性",
          "slug": "webpack和grunt以及gulp相比有什么特性"
        },
        {
          "level": 2,
          "title": "什么时候用Webpack",
          "slug": "什么时候用webpack"
        },
        {
          "level": 2,
          "title": "Webpack的优点与缺点",
          "slug": "webpack的优点与缺点"
        },
        {
          "level": 2,
          "title": "安装 Webpack",
          "slug": "安装-webpack"
        },
        {
          "level": 2,
          "title": "使用 Webpack",
          "slug": "使用-webpack"
        },
        {
          "level": 2,
          "title": "核心概念",
          "slug": "核心概念"
        },
        {
          "level": 3,
          "title": "Entry",
          "slug": "entry"
        },
        {
          "level": 3,
          "title": "Output",
          "slug": "output"
        },
        {
          "level": 3,
          "title": "optimization",
          "slug": "optimization"
        },
        {
          "level": 3,
          "title": "bail",
          "slug": "bail"
        },
        {
          "level": 3,
          "title": "stats",
          "slug": "stats"
        },
        {
          "level": 3,
          "title": "Devtool",
          "slug": "devtool"
        },
        {
          "level": 3,
          "title": "Module",
          "slug": "module"
        },
        {
          "level": 3,
          "title": "Resolve",
          "slug": "resolve"
        },
        {
          "level": 3,
          "title": "Plugin",
          "slug": "plugin"
        },
        {
          "level": 3,
          "title": "devServer",
          "slug": "devserver"
        },
        {
          "level": 3,
          "title": "其它配置项",
          "slug": "其它配置项"
        },
        {
          "level": 3,
          "title": "导出一个 Function",
          "slug": "导出一个-function"
        },
        {
          "level": 3,
          "title": "导出多份配置",
          "slug": "导出多份配置"
        },
        {
          "level": 3,
          "title": "环境变量设置",
          "slug": "环境变量设置"
        },
        {
          "level": 3,
          "title": "整体配置结构",
          "slug": "整体配置结构"
        },
        {
          "level": 2,
          "title": "使用 React 框架",
          "slug": "使用-react-框架"
        },
        {
          "level": 2,
          "title": "使用Vue框架",
          "slug": "使用vue框架"
        },
        {
          "level": 2,
          "title": "性能优化 - 查看 webpack 打包后所有的依赖关系（webpack 可视化工具）",
          "slug": "性能优化-查看-webpack-打包后所有的依赖关系-webpack-可视化工具"
        }
      ]
    }
  ],
  "themeConfig": {
    "logo": "/img/logo.png",
    "nav": [
      {
        "text": "首页",
        "link": "/"
      },
      {
        "text": "前端技术",
        "ariaLabel": "Language Menu",
        "items": [
          {
            "text": "已整理",
            "link": "/clientDocument/"
          },
          {
            "text": "未整理",
            "link": "/undivided/commitLint"
          }
        ]
      },
      {
        "text": "服务端技术",
        "link": "/serverDocument/index"
      },
      {
        "text": "如何更新？",
        "link": "/undivided/updateDoc"
      },
      {
        "text": "关于我",
        "link": "https://blog.csdn.net/baidu_39812199?spm=1001.2101.3001.5343"
      }
    ],
    "sidebar": {
      "/undivided/": [
        {
          "title": "规范",
          "collapsable": true,
          "children": [
            "commitLint"
          ]
        },
        "微前端",
        {
          "title": "vue3.0",
          "collapsable": true,
          "children": [
            "CompositionAPI",
            "扩展"
          ]
        },
        {
          "title": "TS",
          "collapsable": true,
          "children": [
            "typeScript"
          ]
        },
        {
          "title": "ES6",
          "collapsable": true,
          "children": [
            "ES6"
          ]
        },
        {
          "title": "lodash",
          "collapsable": true,
          "children": [
            "lodash"
          ]
        },
        "熟悉Webpack"
      ],
      "/clientDocument/": [
        {
          "title": "about",
          "children": [
            "index"
          ]
        }
      ],
      "/serverDocument/": [
        {
          "title": "about",
          "collapsable": true,
          "sidebarDepth": 1,
          "children": [
            "index"
          ]
        }
      ]
    }
  }
}